spring.application.name=development

# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://trafin_finance_user:DK99fIwO0S9VIDv9FUrCk7LafmY4QjST@dpg-d08kobre5dus73fthjr0-a:5432/trafin_finance
spring.datasource.username=trafin_finance_user
spring.datasource.password=DK99fIwO0S9VIDv9FUrCk7LafmY4QjST
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# JWT Secret key
jwt.secret=12345678
jwt.expiration=360000

# spring.security.user.name=user
# spring.security.user.password=78fa095d-3f4c-48b1-ad50-e24c31d5cf35
