# Application name
spring.application.name=trafindemo

# PostgreSQL database configuration from Render
spring.datasource.url=jdbc:postgresql://dpg-d08vm6h5pdvs739uqsj0-a.oregon-postgres.render.com:5432/trafindatabase
spring.datasource.username=trafindatabase_user
spring.datasource.password=NiObZvYGVespxpupdvSYnVJ4lExMpie0
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


 # JWT Secret key
 jwt.secret=12345678
 jwt.expiration=360000

# Server port (default to 8080 if PORT env variable not set)
server.port=${PORT:8080}
